### ISSUE TITLE
Is there a timeline on code release?

### ISSUE THREAD

**Issue by jsedoc** [passing2961/EmpGPT-3#1]
Great work. We'd love to use your model as a baseline.

**Comment by passing2961** [comment]
Thank you for your attention to our work. Yes, we will release our code after organizing our code. By the way, which model do you want to use, BlenderBot?

**Comment by coolLxx** [comment]
When will the code be released? It's been a long time.

**Comment by passing2961** [comment]
Oh really sorry for that. This week, I will upload it. I really really sorry for that

**Comment by coolLxx** [comment]
> Oh really sorry for that. This week, I will upload it. I really really sorry for that

Thank you. That would be great.

**Comment by passing2961** [comment]
@coolLxx We are very sorry for the late code sharing. Now, you can use our code. If you have any question or find an error or bug, please let us know :)

**Comment by coolLxx** [comment]
> @coolLxx We are very sorry for the late code sharing. Now, you can use our code. If you have any question or find an error or bug, please let us know :)

I really appreciate your help！

**Comment by passing2961** [comment]
I will close this issue.
