### ISSUE TITLE
A tiny typo

### ISSUE THREAD

**Issue by 57one** [passing2961/EmpGPT-3#3]
Thanks for your work.

-----
In https://github.com/passing2961/EmpGPT-3/blob/main/emp_gpt3.py  219
```
215            _ret = {
216               'prompt_input': input_prompt,
217                'dialog': conv,
218                'gold_resp': gold_resp,
219                'gold_emo': gold_emo
220            }
```
here _ret['gold_emo'] stores gold_emo

but in https://github.com/passing2961/EmpGPT-3/blob/main/evaluate.py 465
```
464        gold_resp = example['gold_resp']
465        gold_emotion = example['gold_emotion'] # for single turn
```
-----
By the way, i dont know how to acquire word2count.pkl, did you acquire word2count.pkl with **.jsonl or follow the [original repository](https://github.com/facebookresearch/ParlAI/tree/controllable_dialogue_archive/projects/controllable_dialogue) to generate word2count.pkl with the raw data?

**Comment by passing2961** [comment]
Thanks for finding the typo :) We will fix it.

To get `word2count.pkl`, we follow the original repository with the `empathetic dialogues` raw data.

**Comment by 57one** [comment]
Thank you.
